import type { Metadata } from "next";
import { Poppins } from "next/font/google";
import "./globals.css";
import Sidebar from "@/components/Sidebar/Sidebar";
import { Toaster } from "@/components/ui/toaster";
import { Providers } from "./providers";
import NextTopLoader from 'nextjs-toploader';

const poppins = Poppins({
  subsets: ["latin"],
  weight: ["100", "200", "300", "400", "500", "600", "700", "800", "900"],
});

export const metadata: Metadata = {
  title: "Class Academy",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <link rel="icon" href="/logo.svg" />
      <body className={poppins.className}>
        <Providers >
        <NextTopLoader color="#FF6384" />
          <Sidebar />
          <div className="ml-[20%] w-[80%]">{children}</div>
          <Toaster />
        </Providers>
      </body>
    </html>
  );
}
